# Generated by Django 5.2.11 on 2026-02-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenantmembership_department_and_more'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='roles.role'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('custom', 'Custom')], default='staff', max_length=32),
        ),
    ]
