# Generated by Django 5.2.11 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantmembership_custom_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='staff_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
