# Generated by Django 5.1.4 on 2026-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_2fa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Office Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Personal Phone'),
        ),
    ]
