# Generated by Django 5.1.4 on 2026-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_office_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Nepal PAN (9-digit) — used for TDS reporting', max_length=20),
        ),
    ]
