# Generated by Django 5.2.11 on 2026-02-24 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='coin_to_money_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='How many currency units one coin equals (e.g. 10 = 1 coin = Rs. 10)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='NPR', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=16),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Used as subdomain, e.g. acme → acme.nexusbms.com', max_length=64, unique=True),
        ),
    ]
