# Generated by Django 5.2.11 on 2026-02-25 08:34

from django.db import migrations, models


def nullify_empty_custom_domains(apps, schema_editor):
    """Convert existing empty-string custom_domain values to NULL.
    This must run AFTER the column has been made nullable but BEFORE
    the unique constraint is added."""
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.filter(custom_domain='').update(custom_domain=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_custom_domain'),
    ]

    operations = [
        # Step 1: make the column nullable (no unique yet)
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(
                blank=True, null=True, default=None, max_length=255,
                help_text='Custom domain, e.g. bms.els.com. Leave blank to use subdomain only.',
            ),
        ),
        # Step 2: nullify any existing empty strings now that NULL is allowed
        migrations.RunPython(nullify_empty_custom_domains, migrations.RunPython.noop),
        # Step 3: add the unique constraint
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(
                blank=True, null=True, default=None, max_length=255, unique=True,
                help_text='Custom domain, e.g. bms.els.com. Leave blank to use subdomain only.',
            ),
        ),
        # Step 4: update slug help text (cosmetic)
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(
                help_text='Used as subdomain, e.g. acme → acme.bms.techyatra.com.np',
                max_length=64, unique=True,
            ),
        ),
    ]
