# Generated by Django 5.2.11 on 2026-02-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_seed_modules_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name used in the frontend', max_length=64),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_core',
            field=models.BooleanField(default=False, help_text='If True this module is always active regardless of plan (e.g. Staff, Settings)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='key',
            field=models.SlugField(help_text='Machine key, e.g. "tickets", "inventory"', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Human name, e.g. "Ticket System"', max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order in UI'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive plans are hidden from the tenant assignment dropdown'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Which modules are included by default in this plan', related_name='plans', to='tenants.module'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Subscription plan. Null only during initial seed migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.plan'),
        ),
        migrations.AlterField(
            model_name='tenantmoduleoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantmoduleoverride',
            name='note',
            field=models.CharField(blank=True, help_text='Optional reason for this override, e.g. "Grandfathered access"', max_length=255),
        ),
    ]
