# Generated by Django 5.2.11 on 2026-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_jwt_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='jwt_signing_secret',
            field=models.CharField(blank=True, help_text='Per-tenant HMAC secret for JWT binding. Auto-generated on first save. Rotate to invalidate all tenant tokens.', max_length=64),
        ),
    ]
