# Generated by Django 5.2.11 on 2026-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_tenant_jwt_signing_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#4f46e5', help_text='Primary brand colour in hex (e.g. #4f46e5). Used by the mobile app for dynamic theming.', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sla_warn_before_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Send SLA breach warning this many minutes before the deadline.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', max_length=64),
        ),
    ]
