# Generated by Django 5.1.4 on 2026-03-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True, help_text='URL of the tenant logo displayed in the sidebar and app header.'),
        ),
    ]
