# Generated by Django 5.1.4 on 2026-04-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_add_product_has_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server hostname, e.g. smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('_encrypted_password', models.TextField(blank=True, db_column='encrypted_password', help_text='Encrypted SMTP password — set via the password property, never directly.')),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(help_text='Envelope/From address, e.g. support@yourcompany.com', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Friendly sender name, e.g. Acme Support', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='False = fall back to global SMTP even if config exists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant SMTP Config',
                'verbose_name_plural': 'Tenant SMTP Configs',
            },
        ),
    ]
