# Generated by Django 5.1.4 on 2026-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_add_tenant_smtp_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, help_text='9-digit PAN number issued by IRD Nepal. Printed on all tax invoices.', max_length=9),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_reg_number',
            field=models.CharField(blank=True, help_text='VAT registration number issued by IRD Nepal (if registered for VAT). Printed on tax invoices.', max_length=20),
        ),
    ]
