# Generated by Django 5.1.4 on 2026-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_add_hrm_module_to_pro_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='task_coin_reward',
            field=models.PositiveSmallIntegerField(default=1, help_text='Coins awarded to staff when a project task is completed.'),
        ),
    ]
