# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_add_task_coin_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payslip_calendar',
            field=models.CharField(
                choices=[
                    ('ad', 'Gregorian (AD)'),
                    ('bs', 'Nepali Bikram Sambat (BS)'),
                ],
                default='ad',
                help_text='Calendar used for monthly payslip generation and scheduling.',
                max_length=2,
            ),
        ),
    ]
