# Generated by Django 5.2.11 on 2026-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_status', 'Ticket Status Changed'), ('ticket_comment', 'Ticket Comment'), ('ticket_transfer', 'Ticket Transferred'), ('sla_warning', 'SLA Warning'), ('sla_breached', 'SLA Breached'), ('coin_approved', 'Coin Approved'), ('coin_rejected', 'Coin Rejected'), ('project_assigned', 'Project Assigned'), ('task_assigned', 'Task Assigned'), ('task_done', 'Task Completed'), ('low_stock', 'Low Stock Alert'), ('po_status', 'Purchase Order Update'), ('return_status', 'Return Order Update'), ('general', 'General')], default='general', max_length=32),
        ),
    ]
