# Generated by Django 5.1.4 on 2026-04-03 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_tenantmembership_pan_number'),
        ('tenants', '0017_tenant_add_pan_vat_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('code', models.SlugField(max_length=30)),
                ('days_allowed', models.PositiveSmallIntegerField(help_text='Default days allowed per year for new balances.')),
                ('is_paid', models.BooleanField(default=True, help_text='Unpaid leave triggers a salary deduction in payslip.')),
                ('carry_forward', models.BooleanField(default=False, help_text='Unused balance carries forward to the next BS year.')),
                ('max_carry_forward_days', models.PositiveSmallIntegerField(default=0, help_text='Maximum days that can carry forward. 0 = unlimited.')),
                ('requires_approval', models.BooleanField(default=True, help_text='Public holidays do not require approval.')),
                ('gender_restriction', models.CharField(choices=[('none', 'No restriction'), ('male', 'Male only'), ('female', 'Female only')], default='none', help_text='Maternity = female_only; Paternity = male_only.', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, help_text='Computed working days (weekends excluded).', max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list, help_text='[{"name": str, "url": str}]')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hrm.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'staff', 'status'], name='hrm_leavere_tenant__c6a6dd_idx'), models.Index(fields=['tenant', 'staff', 'start_date'], name='hrm_leavere_tenant__07518f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(help_text='Bikram Sambat year (e.g. 2081).')),
                ('allocated', models.DecimalField(decimal_places=1, help_text='Days allocated this year (may differ from LeaveType.days_allowed for HR overrides).', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Days carried forward from the previous year.', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Days consumed by approved leave requests.', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hrm.leavetype')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'staff', 'year'], name='hrm_leaveba_tenant__4e827e_idx')],
                'unique_together': {('tenant', 'staff', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_profile', to='accounts.tenantmembership')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'membership'], name='hrm_staffpr_tenant__c90c34_idx')],
            },
        ),
    ]
