# Generated by Django 5.1.4 on 2026-04-04 02:55

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_shift_shiftassignment_attendance_upgrade'),
        ('tenants', '0019_add_task_coin_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancepolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={},
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='hrm_attenda_tenant__a8f158_idx',
            old_name='hrm_attend_tenant__staff_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='hrm_attenda_tenant__4adbc8_idx',
            old_name='hrm_attend_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='hrm_shiftas_tenant__fb35fc_idx',
            old_name='hrm_shiftas_tenant__idx',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='deduct_absent',
            field=models.BooleanField(default=True, help_text='Deduct one daily-rate from payslip for each Absent day.'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='deduct_late',
            field=models.BooleanField(default=True, help_text='Deduct proportional amount from payslip for late minutes.'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='expected_end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Expected clock-out time (local timezone).'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='expected_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Expected clock-in time (local timezone).'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='grace_period_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Per-arrival grace window subtracted from measured lateness.'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='half_day_threshold_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.0'), help_text='Work hours below this → status downgraded to Half Day.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='late_deduction_grace_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Total late minutes per pay period allowed before deduction is applied. Prevents penalising minor cumulative lateness.'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='late_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes after expected_start_time before staff is marked Late.'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='work_days',
            field=models.JSONField(default=list, help_text='List of Python weekday() integers that count as work days. Mon=0, Tue=1, Wed=2, Thu=3, Fri=4, Sat=5, Sun=6. Nepal default: [0,1,2,3,4,6].'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clocked_in_by',
            field=models.ForeignKey(blank=True, help_text='Set when a manager manually marks attendance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='grace_period_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes late before Staff is marked Late.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-assigned when no ShiftAssignment exists for a staff.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='late_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes after start_time + grace before marking Late.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='min_work_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.0'), help_text='Minimum hours to avoid Half Day status.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='shift',
            name='overtime_after_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), help_text='Hours beyond which work is counted as overtime.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='shift',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='effective_from',
            field=models.DateField(help_text='First day this assignment is active.'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Last day active. Null = still current.', null=True),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
    ]
