# Generated by Django 5.2.11 on 2026-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_team_members_projectattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number to contact for this project', max_length=32),
        ),
    ]
