# Generated by Django 5.2.11 on 2026-02-27 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_nepal_address_optional_email'),
        ('projects', '0006_add_project_product_request'),
        ('tenants', '0008_alter_module_icon_alter_module_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='project_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'is_deleted'], name='project_tenant_deleted_idx'),
        ),
    ]
