# Generated by Django 5.1.4 on 2026-03-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_product_has_warranty'),
        ('projects', '0009_alter_projectmemberschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproduct',
            name='serial_number',
            field=models.ForeignKey(blank=True, help_text='Required if product has warranty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_usages', to='inventory.serialnumber'),
        ),
    ]
