# Generated by Django 5.1.4 on 2026-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_project_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when task.overdue event was last fired — prevents re-firing on every beat run.', null=True),
        ),
    ]
