# Generated by Django 5.2.11 on 2026-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='source_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('task', 'Task'), ('manual', 'Manual')], default='ticket', max_length=32),
        ),
    ]
