# Generated by Django 5.2.11 on 2026-02-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_quotation_debitnote_tds_bankreconciliation_recurringjournal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Finance Review'), ('approved', 'Finance Approved'), ('rejected', 'Finance Rejected')], default='draft', help_text='Approval state for ticket-linked invoices.', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Method used when staff collected payment (cash/bank_transfer/esewa/…)', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
