# Generated by Django 5.2.11 on 2026-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_invoice_finance_notes_invoice_finance_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payslip', 'Payslip'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
