# Generated by Django 5.2.11 on 2026-03-10 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_staffsalaryprofile_add_created_by'),
        ('tenants', '0012_tenant_primary_color_tenant_sla_warn_before_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payslip', 'Payslip'), ('manual', 'Manual'), ('cogs', 'COGS'), ('vat_remittance', 'VAT Remittance'), ('tds_remittance', 'TDS Remittance')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other deductions (advances, damages, etc.)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='staffsalaryprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
    ]
