# Generated by Django 5.1.4 on 2026-04-02 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_journalentry_reference_type_and_more'),
        ('tenants', '0016_add_tenant_smtp_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=120),
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowances',
            field=models.JSONField(default=list, help_text='List of {"label": str, "amount": str} allowance line items'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager/Admin who approved this payslip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals & Entertainment'), ('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance & Repairs'), ('marketing', 'Marketing & Advertising'), ('training', 'Training & Development'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('receipt_url', models.CharField(blank=True, help_text='S3/MinIO URL of uploaded receipt', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted to Ledger'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recur_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], help_text='Repeat interval for recurring expenses', max_length=16)),
                ('next_recur_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Expense account in CoA to post this to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Set when expense is posted to ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='accounting.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_expenses', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='acc_expense_tenant_status_idx'), models.Index(fields=['tenant', 'date'], name='acc_expense_tenant_date_idx'), models.Index(fields=['tenant', 'category'], name='acc_expense_tenant_cat_idx')],
            },
        ),
    ]
