# Generated by Django 5.1.4 on 2026-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_expense_payslip_allowances_bank_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('issued', 'Issued'), ('presented', 'Presented to Bank'), ('cleared', 'Cleared'), ('bounced', 'Bounced')], help_text='Cheque lifecycle status. Only applicable when method=cheque.', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='party_name',
            field=models.CharField(blank=True, help_text='Payee name (outgoing) or payer/drawer name (incoming). Used for cheque tracking.', max_length=200),
        ),
    ]
