# Generated by Django 5.1.4 on 2026-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_payment_add_cheque_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_pan',
            field=models.CharField(blank=True, help_text='Buyer PAN number (9 digits) for B2B tax invoices — required by IRD for CBMS reporting.', max_length=9),
        ),
    ]
