# Generated by Django 5.1.4 on 2026-04-02 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_invoice_add_buyer_pan'),
        ('tenants', '0017_tenant_add_pan_vat_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=16)),
                ('report_section', models.CharField(blank=True, choices=[('bs_fixed_assets', 'BS: Fixed Assets'), ('bs_investments', 'BS: Investments'), ('bs_current_assets', 'BS: Current Assets'), ('bs_capital', 'BS: Capital & Equity'), ('bs_loans', 'BS: Loans & Borrowings'), ('bs_current_liabilities', 'BS: Current Liabilities'), ('pnl_gross', 'P&L: Gross Profit Section'), ('pnl_net', 'P&L: Net Profit Section')], max_length=32)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=8)),
                ('affects_gross_profit', models.BooleanField(default=False, help_text='True for Sales, COGS, and Direct Expense groups — used to compute Gross Profit.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within report section.')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='accounting.accountgroup')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Account group (Tally-style primary group). Required for new accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.accountgroup'),
        ),
    ]
