# Generated by Django 5.1.4 on 2026-04-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_accountgroup'),
        ('tenants', '0017_tenant_add_pan_vat_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_reversal',
            field=models.BooleanField(default=False, help_text='True when this entry was auto-generated as a reversal.'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_date',
            field=models.DateField(blank=True, help_text='If set, a reversing entry is auto-created on this date.', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.OneToOneField(blank=True, help_text='The reversing entry once created (set by the reversal task).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='accounting.journalentry'),
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.costcentre')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_centre',
            field=models.ForeignKey(blank=True, help_text='Optional cost centre for management P&L reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.costcentre'),
        ),
        migrations.CreateModel(
            name='FiscalYearClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy_year', models.PositiveSmallIntegerField(db_index=True, help_text='Nepali BS year closed (e.g. 2081 means FY 2081/082).')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('retained_earnings_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net profit/loss transferred to Retained Earnings.', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, help_text='The closing journal entry that moved P&L to Retained Earnings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_year_close', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-fy_year'],
                'abstract': False,
                'unique_together': {('tenant', 'fy_year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-allocated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'payment'], name='acc_payalloc_pmt_idx'), models.Index(fields=['tenant', 'invoice'], name='acc_payalloc_inv_idx'), models.Index(fields=['tenant', 'bill'], name='acc_payalloc_bill_idx')],
            },
        ),
    ]
