# Generated by Django 5.1.4 on 2026-04-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_add_cost_centre_fiscal_year_close_payment_alloc_reversing_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, help_text="Bill date from the supplier's invoice. Used as GL posting date on approve.", null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, help_text='Invoice / voucher date used for GL posting.  Defaults to creation date.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Ledger account for direct Dr/Cr when not linked to an invoice or bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payments', to='accounting.account'),
        ),
    ]
