# Generated by Django 5.1.4 on 2026-04-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_payslip_deduction_breakdown'),
        ('inventory', '0009_product_is_bundle_productbundle_supplierpayment'),
        ('tenants', '0017_tenant_add_pan_vat_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='acc_journal_one_per_doc_purpose',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='acc_bill_tenant_status',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='acc_bill_tenant_date',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_inv_tenant_status',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_inv_tenant_date',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='acc_inv_tenant_due_date',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_tenant_date',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_tenant_ref',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_tenant_posted',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='acc_pay_tenant_date',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='acc_pay_tenant_type',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annual rate for WDV method (e.g. 0.20 = 20%). Leave blank for SLM — rate is auto-computed from useful_life_months.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payslip', 'Payslip'), ('manual', 'Manual'), ('cogs', 'COGS'), ('vat_remittance', 'VAT Remittance'), ('tds_remittance', 'TDS Remittance'), ('fiscal_year_close', 'Fiscal Year Close'), ('depreciation', 'Depreciation'), ('fx_gain_loss', 'FX Gain/Loss')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_posted', True), models.Q(('reference_type', 'manual'), _negated=True), models.Q(('reference_type', 'fiscal_year_close'), _negated=True), models.Q(('reference_type', 'vat_remittance'), _negated=True), models.Q(('reference_type', 'tds_remittance'), _negated=True), ('reference_id__isnull', False)), fields=('tenant', 'reference_type', 'reference_id', 'purpose'), name='acc_journal_one_per_doc_purpose'),
        ),
    ]
