# Generated by Django 5.1.4 on 2026-04-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_expense_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Expense account in CoA to post this to (Dr side)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payslip', 'Payslip'), ('expense', 'Expense'), ('manual', 'Manual'), ('cogs', 'COGS'), ('vat_remittance', 'VAT Remittance'), ('tds_remittance', 'TDS Remittance'), ('fiscal_year_close', 'Fiscal Year Close'), ('depreciation', 'Depreciation'), ('fx_gain_loss', 'FX Gain/Loss')], default='manual', max_length=20),
        ),
    ]
