# Generated by Django 5.1.4 on 2026-04-03 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_add_ref_expense_choice'),
        ('tenants', '0017_tenant_add_pan_vat_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='acc_journal_one_per_doc_purpose',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payslip', 'Payslip'), ('expense', 'Expense'), ('manual', 'Manual'), ('cogs', 'COGS'), ('vat_remittance', 'VAT Remittance'), ('tds_remittance', 'TDS Remittance'), ('fiscal_year_close', 'Fiscal Year Close'), ('depreciation', 'Depreciation'), ('fx_gain_loss', 'FX Gain/Loss'), ('recurring', 'Recurring Journal')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_posted', True), models.Q(('reference_type', 'manual'), _negated=True), models.Q(('reference_type', 'fiscal_year_close'), _negated=True), models.Q(('reference_type', 'vat_remittance'), _negated=True), models.Q(('reference_type', 'tds_remittance'), _negated=True), models.Q(('reference_type', 'recurring'), _negated=True), ('reference_id__isnull', False)), fields=('tenant', 'reference_type', 'reference_id', 'purpose'), name='acc_journal_one_per_doc_purpose'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_posted', True), ('reference_type', 'recurring'), ('reference_id__isnull', False)), fields=('tenant', 'reference_type', 'reference_id', 'date'), name='acc_journal_one_recurring_per_date'),
        ),
    ]
