# Generated by Django 5.1.4 on 2026-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_recurring_journal_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted for unpaid leave (unpaid_days × daily_rate).', max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of unpaid leave days in this pay period.', max_digits=5),
        ),
    ]
