# Generated by Django 5.1.4 on 2026-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_hrm_payslip_leave_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_category',
            field=models.CharField(blank=True, help_text='Free-text label used when category=custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals & Entertainment'), ('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance & Repairs'), ('marketing', 'Marketing & Advertising'), ('training', 'Training & Development'), ('other', 'Other'), ('custom', 'Custom')], db_index=True, default='other', max_length=32),
        ),
    ]
