# Generated by Django 5.1.4 on 2026-04-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_expense_custom_category'),
        ('inventory', '0011_remove_supplier_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Optional link to a service from the service catalog', limit_choices_to={'is_deleted': False, 'is_service': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.product'),
        ),
    ]
