# Generated by Django 5.2.11 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('accounting', '0031_payslip_attendance_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Canonical counterparty for this bill. Temporary optional during migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='parties.party'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Canonical counterparty for this invoice. Temporary optional during migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='parties.party'),
        ),
        migrations.AddField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Canonical counterparty for this payment when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parties.party'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Canonical counterparty for this quotation. Temporary optional during migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='parties.party'),
        ),
    ]
