# Generated by Django 5.2.11 on 2026-02-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketsla_breached_at_ticketsla_warning_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_attachments', to='tickets.ticketcomment'),
        ),
    ]
