# Generated by Django 5.2.11 on 2026-02-24 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_sprint3_category_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/tickets/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
