# Generated by Django 5.2.11 on 2026-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_team_members_ticketattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number to contact for this ticket', max_length=32),
        ),
    ]
