# Generated by Django 5.2.11 on 2026-02-26 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_module_icon_alter_module_id_and_more'),
        ('tickets', '0007_add_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Company Hilux', max_length=128)),
                ('plate_number', models.CharField(blank=True, help_text='License plate', max_length=32)),
                ('type', models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('van', 'Van'), ('truck', 'Truck'), ('other', 'Other')], default='car', max_length=16)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=16)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Billing rate per km in tenant currency', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('odometer_start', models.DecimalField(decimal_places=1, max_digits=10)),
                ('odometer_end', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fuel money spent', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driven_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to='tickets.ticket')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='tickets.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
