# Generated by Django 5.2.11 on 2026-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_vehicle_and_vehiclelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.vehicle'),
        ),
    ]
