# Generated by Django 5.2.11 on 2026-02-27 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_nepal_address_optional_email'),
        ('departments', '0002_sprint2_fields'),
        ('tenants', '0008_alter_module_icon_alter_module_id_and_more'),
        ('tickets', '0009_ticket_vehicles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'status'], name='ticket_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'assigned_to'], name='ticket_tenant_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'is_deleted'], name='ticket_tenant_deleted_idx'),
        ),
    ]
