# Generated by Django 5.2.11 on 2026-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_indexes_and_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service/labour fee for this ticket (separate from product costs).', max_digits=12),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='coin_product_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='% of product sale value awarded as coins (e.g. 1 = 1%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='coin_service_rate',
            field=models.DecimalField(decimal_places=2, default=25, help_text='% of service charge value awarded as coins (e.g. 25 = 25%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_free_service',
            field=models.BooleanField(default=False, help_text='When true, no invoice is generated. Coins still awarded at service rate.'),
        ),
    ]
