# Generated by Django 5.2.11 on 2026-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_service_charge_tickettype_coin_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0–100). e.g. 10 = 10% off unit_price.', max_digits=5),
        ),
    ]
