# Generated by Django 5.1.4 on 2026-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticketproduct_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='author_override',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
