# Generated by Django 5.1.4 on 2026-04-03 12:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_add_hrm_module_to_pro_plan'),
        ('tickets', '0015_add_brand_model_to_category_and_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service/labour fee for this ticket (separate from product costs).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['tenant', 'breached', 'breach_at'], name='sla_tenant_breach_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['tenant', 'breach_at'], name='sla_tenant_breach_at_idx'),
        ),
    ]
