# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_add_hrm_module_to_pro_plan'),
        ('tickets', '0016_sla_indexes_service_charge_validator_vehiclelog_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
