# Generated by Django 5.2.11 on 2026-03-10 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0012_tenant_primary_color_tenant_sla_warn_before_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='My Website', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=512)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/favicons/')),
                ('theme_key', models.CharField(blank=True, help_text='Theme identifier selected from AI-generated options or library', max_length=64)),
                ('primary_color', models.CharField(default='#4F46E5', help_text='Hex colour, e.g. #4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#7C3AED', help_text='Hex colour, e.g. #7C3AED', max_length=7)),
                ('font_family', models.CharField(default='Inter', help_text='Google Font name', max_length=64)),
                ('custom_head_script', models.TextField(blank=True, help_text='HTML/JS injected into <head> on every page')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('default_meta_title', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'CMS Site',
                'verbose_name_plural': 'CMS Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('standard', 'Standard'), ('contact', 'Contact'), ('blog_index', 'Blog Index'), ('landing', 'Landing Page')], default='standard', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL segment, e.g. "about".  Home page = ""', max_length=128)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Order in navigation menu')),
                ('show_in_nav', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cms.cmssite')),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CMSGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('prompt', models.TextField(help_text="User's description of their business / desired site")),
                ('design_options', models.JSONField(blank=True, default=list, help_text='List of AI-generated design variants')),
                ('selected_design_index', models.SmallIntegerField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='cms.cmssite')),
            ],
            options={
                'verbose_name': 'CMS Generation Job',
                'verbose_name_plural': 'CMS Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSCustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, help_text='e.g. www.mycompany.com', max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('txt_record', models.CharField(blank=True, help_text='DNS TXT value for domain ownership verification', max_length=64)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Certificate Active'), ('failed', 'Provisioning Failed')], default='pending', max_length=16)),
                ('ssl_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to='cms.cmssite')),
            ],
            options={
                'verbose_name': 'CMS Custom Domain',
                'verbose_name_plural': 'CMS Custom Domains',
            },
        ),
        migrations.CreateModel(
            name='CMSBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary (used in listing cards)')),
                ('body', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cms/blog/')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of string tags, e.g. ["news", "update"]')),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=1)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_blog_posts_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='cms.cmssite')),
            ],
            options={
                'verbose_name': 'CMS Blog Post',
                'verbose_name_plural': 'CMS Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero Banner'), ('text', 'Rich Text'), ('services', 'Services Grid'), ('gallery', 'Image Gallery'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('contact_form', 'Contact Form'), ('pricing', 'Pricing Table'), ('team', 'Team Members'), ('faq', 'FAQ Accordion'), ('html', 'Custom HTML'), ('video', 'Video Embed'), ('stats', 'Stats / Numbers')], db_index=True, max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Block-specific data payload (schema per block_type)')),
                ('raw_html', models.TextField(blank=True, help_text='Sanitized custom HTML (BLOCK_HTML type only)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.cmspage')),
            ],
            options={
                'verbose_name': 'CMS Block',
                'verbose_name_plural': 'CMS Blocks',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['tenant', 'page', 'is_visible'], name='cms_block_tenant_vis_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cmssite',
            index=models.Index(fields=['tenant', 'is_published'], name='cms_site_tenant_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspage',
            index=models.Index(fields=['tenant', 'site', 'is_published'], name='cms_page_tenant_pub_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmspage',
            unique_together={('site', 'slug')},
        ),
        migrations.AddIndex(
            model_name='cmsgenerationjob',
            index=models.Index(fields=['tenant', 'status'], name='cms_genjob_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsgenerationjob',
            index=models.Index(fields=['tenant', 'created_at'], name='cms_genjob_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cmscustomdomain',
            index=models.Index(fields=['tenant', 'is_verified'], name='cms_domain_tenant_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsblogpost',
            index=models.Index(fields=['tenant', 'site', 'is_published'], name='cms_blog_tenant_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsblogpost',
            index=models.Index(fields=['tenant', 'is_deleted'], name='cms_blog_tenant_del_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmsblogpost',
            unique_together={('site', 'slug')},
        ),
    ]
