# Generated by Django 5.1.4 on 2026-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Rendered CSS from GrapeJS.'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Rendered HTML from GrapeJS. Overrides block content in public renderer.'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='grapes_data',
            field=models.JSONField(blank=True, help_text='GrapeJS editor state (components + styles JSON). Phase 2.', null=True),
        ),
    ]
