# Generated by Django 5.1.4 on 2026-03-10 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_grapes_editor_phase2'),
        ('tenants', '0012_tenant_primary_color_tenant_sla_warn_before_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('text', 'Rich Text'), ('services', 'Services Grid'), ('gallery', 'Image Gallery'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('contact_form', 'Contact Form'), ('pricing', 'Pricing Table'), ('team', 'Team Members'), ('faq', 'FAQ Accordion'), ('html', 'Custom HTML'), ('video', 'Video Embed'), ('stats', 'Stats / Numbers'), ('newsletter', 'Newsletter Signup'), ('product_catalog', 'Product Catalogue'), ('blog_preview', 'Blog Preview')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='active', max_length=20)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Which page/block captured this email', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscribers', to='cms.cmssite')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['tenant', 'site', 'status'], name='cms_nl_tenant_site_status_idx')],
                'unique_together': {('tenant', 'site', 'email')},
            },
        ),
    ]
