# Generated by Django 5.1.4 on 2026-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_newsletter_subscriber_new_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsblogpost',
            name='author_name',
            field=models.CharField(blank=True, default='', help_text='Display name for the post author (overrides user full name)', max_length=150),
        ),
    ]
