# Generated by Django 5.1.4 on 2026-04-02 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_blog_author_name'),
        ('customers', '0007_customercontact_created_at_and_more'),
        ('tenants', '0016_add_tenant_smtp_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssite',
            name='announcement_active',
            field=models.BooleanField(default=False, help_text='Show the announcement bar on the public site'),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='announcement_color',
            field=models.CharField(default='#4F46E5', help_text='Background hex colour for the announcement bar', max_length=7),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='announcement_text',
            field=models.CharField(blank=True, help_text='Site-wide announcement banner text', max_length=500),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='footer_nav',
            field=models.JSONField(blank=True, default=list, help_text='Footer navigation links: [{label, url}]'),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='header_nav',
            field=models.JSONField(blank=True, default=list, help_text='Header navigation links: [{label, url, open_new_tab}]'),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cmssite',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='CMSInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('source_page', models.CharField(blank=True, help_text='Page slug where the form was submitted', max_length=128)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('converted', 'Converted to Customer'), ('archived', 'Archived')], db_index=True, default='new', max_length=20)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_note', models.TextField(blank=True, help_text='Internal note from staff when replying')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_inquiry_source', to='customers.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cms.cmssite')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'CMS Inquiry',
                'verbose_name_plural': 'CMS Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'site', 'status'], name='cms_inq_tenant_status_idx'), models.Index(fields=['tenant', 'is_deleted'], name='cms_inq_tenant_del_idx')],
            },
        ),
        migrations.CreateModel(
            name='CMSPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_slug', models.CharField(db_index=True, help_text="Page slug, '' for home, 'product:42' for product views", max_length=200)),
                ('view_date', models.DateField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='cms.cmssite')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'CMS Page View',
                'verbose_name_plural': 'CMS Page Views',
                'ordering': ['-view_date', '-view_count'],
                'indexes': [models.Index(fields=['tenant', 'site', 'view_date'], name='cms_pv_tenant_date_idx')],
                'unique_together': {('tenant', 'site', 'page_slug', 'view_date')},
            },
        ),
    ]
