# Generated by Django 5.1.4 on 2026-04-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_inquiry_pageview_site_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
