# Generated by Django 5.2.11 on 2026-02-24 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_fix_is_active_default'),
        ('tenants', '0003_tenant_coin_to_money_rate_tenant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('email', ''), _negated=True)), fields=('tenant', 'email'), name='unique_customer_email_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', ''), _negated=True)), fields=('tenant', 'phone'), name='unique_customer_phone_per_tenant'),
        ),
    ]
