# Generated by Django 5.2.11 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_unique_email_phone_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
