# Generated by Django 5.2.11 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('customers', '0007_customercontact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='parties.party'),
        ),
    ]
