# Generated by Django 5.2.11 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_add_party_links'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='account',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional per-party sub-ledger account in Chart of Accounts.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='parties',
                to='accounting.account',
            ),
        ),
    ]
