# Generated by Django 5.2.11 on 2026-02-27 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockcount_stockcountitem_supplierproduct'),
        ('tenants', '0008_alter_module_icon_alter_module_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product', 'movement_type'], name='stkmov_tenant_prod_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='stockmov_product_recent_idx'),
        ),
    ]
