# Generated by Django 5.1.4 on 2026-03-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_warranty_fields'),
        ('tenants', '0015_add_product_has_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_warranty',
            field=models.BooleanField(default=False, help_text='Requires serial number tracking when used/sold'),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(help_text='Unique serial/IMEI number', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used / Sold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='available', max_length=20)),
                ('reference_type', models.CharField(blank=True, help_text='Model name where used', max_length=64)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of ticket/project/invoice', null=True)),
                ('notes', models.TextField(blank=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When marked as used', null=True)),
                ('warranty_expires', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'has_warranty': True}, on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'product', 'status'], name='inventory_s_tenant__e0d563_idx'), models.Index(fields=['serial_number'], name='inventory_s_serial__e6e8fe_idx')],
                'unique_together': {('tenant', 'product', 'serial_number')},
            },
        ),
    ]
