# Generated by Django 5.1.4 on 2026-04-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_product_has_warranty'),
        ('tenants', '0016_add_tenant_smtp_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Bundle product — composed of component products'),
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this component per bundle unit')),
                ('bundle', models.ForeignKey(help_text='The parent bundle product', limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='inventory.product')),
                ('component', models.ForeignKey(help_text='Component product included in this bundle', on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='inventory.product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['component__name'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'bundle'], name='inventory_p_tenant__80010a_idx')],
                'unique_together': {('tenant', 'bundle', 'component')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque number, transaction ID, or other reference', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Leave blank for a general supplier payment not tied to a PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.purchaseorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'supplier'], name='inventory_s_tenant__142bc2_idx'), models.Index(fields=['tenant', 'purchase_order'], name='inventory_s_tenant__787d48_idx'), models.Index(fields=['tenant', 'payment_date'], name='inventory_s_tenant__7c77cf_idx')],
            },
        ),
    ]
