# Generated by Django 5.1.4 on 2026-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_is_bundle_productbundle_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Nepal PAN (9-digit)', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Registration Number', max_length=20),
        ),
    ]
