# Generated by Django 5.1.4 on 2026-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplier_pan_number_supplier_vat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='vat_number',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Nepal PAN / VAT number (9-digit)', max_length=20),
        ),
    ]
