# Generated by Django 5.2.11 on 2026-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='Seeded from PRELOAD_ROLES. Name cannot be changed; permissions can.'),
        ),
    ]
