# Generated by Django 5.2.11 on 2026-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postgres_rls'),
    ]

    operations = [
        # BannedIP is kept as an unmanaged model in core/anomaly.py.
        # We remove it from Django's migration state so makemigrations stops
        # proposing changes, but we do NOT drop the actual DB table.
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # no DB change — keep the table
            state_operations=[migrations.DeleteModel(name='BannedIP')],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='row_hash',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 integrity seal. Blank on rows created before 0003.', max_length=64),
        ),
    ]
