# Generated by Django 5.2.11 on 2026-03-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_bannedip_alter_auditlog_row_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('token_refresh', 'Token Refreshed'), ('token_rejected', 'Token Rejected'), ('two_fa_enabled', '2FA Enabled'), ('two_fa_disabled', '2FA Disabled'), ('logout', 'Logout'), ('tenant_created', 'Tenant Created'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_activated', 'Tenant Activated'), ('tenant_deleted', 'Tenant Deleted'), ('slug_change_blocked', 'Slug Change Blocked'), ('plan_changed', 'Plan Changed'), ('module_override_set', 'Module Override Set'), ('module_override_deleted', 'Module Override Deleted'), ('module_toggled', 'Plan Module Toggled'), ('cross_tenant_probe', 'Cross-Tenant Access Attempt'), ('tenant_enum_probe', 'Tenant Enumeration Probe'), ('admin_probe', 'Admin Path Probe from Tenant'), ('superadmin_ip_blocked', 'Superadmin Access IP Blocked'), ('permission_denied', 'Permission Denied'), ('rate_limit_hit', 'Rate Limit Exceeded'), ('staff_deactivated', 'Staff Deactivated'), ('staff_reactivated', 'Staff Reactivated'), ('role_changed', 'Member Role Changed')], db_index=True, max_length=64),
        ),
    ]
